### ISSUE TITLE
[Feature] size label 워크플로우 추가

### ISSUE THREAD

**Issue by soonki-98** [modern-agile-team/9term-main-front#34]
## 🔥 어떤 기능인가요?

PR이 올라가면 size label을 등록하는 워크플로우입니다.

## 💡 기대하는 결과

매 PR이 올라갈때마다 자동으로 size label이 추가됨

  

## 📌 추가 정보

https://github.com/pascalgn/size-label-action

```yaml
# example
name: PR Size Label

on:
  workflow_call:

jobs:
  size-label:
    runs-on: ubuntu-latest

    steps:
      - name: PR 사이즈 레이블 달기
        uses: pascalgn/size-label-action@v0.4.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          sizes: >
            {
              "0": "Baby 🥚",
              "50": "Cute 🐤",
              "200": "Normal 🐔",
              "500": "Hard 🦅",
              "1000": "Horrible 🔥",
              "2000": "Death 🪦"
            }
```
